export const ROUTES = {
  HOME: "/",
  CART: "/cart",
  CHECKOUT: "/checkout",
  CHECKOUT_SUCCESS: "/checkout/success",
  ORDERS: "/orders",
  PROFILE: "/profile",
  PRODUCTS: "/products",
  PRODUCT_DETAIL: (slug: string) => `/products/${slug}`,
  BEST_SELLERS: "/products/best-sellers",
  POSTS: "/posts",
  POST_DETAIL: (slug: string) => `/posts/${slug}`,

  // Dashboard / Admin routes
  DASHBOARD: {
    ROOT: "/dashboard",
    CATEGORIES: "/dashboard/categories",
    ORDERS: "/dashboard/orders",
    ORDER_DETAIL: (id: string) => `/dashboard/orders/${id}`,
    PRODUCTS: "/dashboard/products",
    PRODUCT_DETAIL: (id: string) => `/dashboard/products/${id}`,
    PURCHASE_ORDERS: "/dashboard/purchase-orders",
    RETURN_REQUESTS: "/dashboard/return-requests",
    RETURN_REQUEST_DETAIL: (id: string) => `/dashboard/return-requests/${id}`,
    REVIEWS: "/dashboard/reviews",
    SHIPMENTS: "/dashboard/shipments",
    SHIPMENT_DETAIL: (id: string) => `/dashboard/shipments/${id}`,
    STOCK_MOVEMENTS: "/dashboard/stock-movements",
    SUPPLIERS: "/dashboard/suppliers",
    SUPPLIER_DETAIL: (id: string) => `/dashboard/suppliers/${id}`,
    USERS: "/dashboard/users",
    VOUCHERS: "/dashboard/vouchers",
    VOUCHER_DETAIL: (id: string) => `/dashboard/vouchers/${id}`,
    WAREHOUSES: "/dashboard/warehouses",
    WAREHOUSE_DETAIL: (id: string) => `/dashboard/warehouses/${id}`,
    POSTS: "/dashboard/posts",
    POST_DETAIL: (id: string) => `/dashboard/posts/${id}`,
  },
} as const;
